/* GENERATED by scripts/build-tokens.mjs from design-system/tokens.json — do not edit by hand. */
export const tokens = {
  color: {
    "paper": "#f4f3ef",
    "surface": "#faf9f6",
    "surface-2": "#efece5",
    "ink": "#17160f",
    "fg": "#26241b",
    "dim": "#57544a",
    "faint": "#8b877b",
    "line": "#ddd9cf",
    "line-strong": "#c9c4b7",
    "accent": "#2438c9",
    "accent-hover": "#1c2ea8",
    "accent-ink": "#ffffff",
    "on-ink": "#f4f3ef"
  },
  status: {
    "beta": "#2438c9",
    "beta-bg": "#e7e9fb",
    "testflight": "#1f6f8b",
    "testflight-bg": "#e2eef2",
    "soon": "#8b877b",
    "soon-bg": "#ece9e1"
  },
  font: {
    "display": "'Archivo', system-ui, -apple-system, 'Segoe UI', sans-serif",
    "serif": "'Newsreader', Georgia, 'Times New Roman', serif",
    "mono": "'IBM Plex Mono', ui-monospace, 'SFMono-Regular', Menlo, monospace"
  },
  weight: {
    "reg": "400",
    "med": "500",
    "semi": "600",
    "bold": "800",
    "black": "900"
  },
  size: {
    "hero": "clamp(40px, 6.4vw, 82px)",
    "h2": "clamp(28px, 4vw, 46px)",
    "h3": "30px",
    "lead": "22px",
    "body": "18px",
    "sm": "15px",
    "label": "12px",
    "mono-sm": "13.5px"
  },
  leading: {
    "tight": "1.02",
    "snug": "1.2",
    "body": "1.6"
  },
  tracking: {
    "tight": "-0.03em",
    "normal": "0",
    "label": "0.14em"
  },
  space: {
    "1": "4px",
    "2": "8px",
    "3": "12px",
    "4": "16px",
    "5": "22px",
    "6": "32px",
    "7": "48px",
    "8": "72px",
    "9": "96px"
  },
  radius: {
    "sm": "2px",
    "md": "4px",
    "pill": "20px"
  },
  layout: {
    "maxw": "1080px",
    "gutter": "32px"
  },
  motion: {
    "fast": "140ms",
    "base": "220ms",
    "ease": "cubic-bezier(.2,.6,.2,1)"
  },
  shadow: {
    "card": "0 1px 2px rgba(23,22,15,.04), 0 10px 30px rgba(23,22,15,.06)"
  }
};

/** cssVar("color","accent") -> "var(--color-accent)" */
export const cssVar = (group, key) => `var(--${group}-${key})`;
export default tokens;
