/* Zero-dependency token generator (no Style Dictionary install needed; SD-compatible shape).
   Source of truth: design-system/tokens.json → app/tokens.css (CSS custom props) + lib/tokens.js (JS).
   Run: npm run tokens  */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = JSON.parse(readFileSync(join(root, "design-system/tokens.json"), "utf8"));

const GROUPS = ["color", "status", "font", "weight", "size", "leading", "tracking", "space", "radius", "layout", "motion", "shadow"];
const lines = [];
for (const g of GROUPS) {
  const grp = src[g];
  if (!grp) continue;
  lines.push(`  /* ${g} */`);
  for (const [k, v] of Object.entries(grp)) lines.push(`  --${g}-${k}: ${v};`);
}
const css = `/* GENERATED by scripts/build-tokens.mjs from design-system/tokens.json — do not edit by hand. */
:root {
${lines.join("\n")}
}
`;
mkdirSync(join(root, "app"), { recursive: true });
mkdirSync(join(root, "lib"), { recursive: true });
writeFileSync(join(root, "app/tokens.css"), css);

const jsBody = GROUPS.filter((g) => src[g]).map((g) => `  ${g}: ${JSON.stringify(src[g], null, 2).replace(/\n/g, "\n  ")}`).join(",\n");
const js = `/* GENERATED by scripts/build-tokens.mjs from design-system/tokens.json — do not edit by hand. */
export const tokens = {
${jsBody}
};

/** cssVar("color","accent") -> "var(--color-accent)" */
export const cssVar = (group, key) => \`var(--\${group}-\${key})\`;
export default tokens;
`;
writeFileSync(join(root, "lib/tokens.js"), js);

const nCss = lines.filter((l) => l.trim().startsWith("--")).length;
console.log(`tokens: wrote app/tokens.css (${nCss} custom properties) + lib/tokens.js`);
